<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

	public function getCommentsWithAdvert($limit){
		$qb = $this->createQueryBuilder('co');

		$qb
			->innerJoin('co.advert', 'adv')
			->addSelect('adv');

		$qb->setMaxResults($limit);

		return $qb
			->getQuery()
			->getResult();
	}
}
